format = "$character"
right_format = "$directory"
command_timeout = 1000

[directory]
truncate_to_repo = false
truncation_length = 1
fish_style_pwd_dir_length = 1
style = "#ffffff"
format = "[>]($style) [$path$read_only](#ffffff) "
home_symbol = "~"
read_only = '!'
truncation_symbol = '.../'
