format = "$sudo$username$character"
right_format = "$directory"
command_timeout = 1000

[directory]
truncate_to_repo = false
truncation_length = 1
fish_style_pwd_dir_length = 1
style = "#bebebe"
format = "[>]($style) [$path$read_only](#bebebe) "
home_symbol = "~"
read_only = '!'
truncation_symbol = '.../'
[git_metrics]
disabled = true

[git_branch]
disabled = true

[git_status]
disabled = true

[python]
symbol = "py"
format = "\\[[$version]($style)\\]"
version_format = "py${major}.${minor}"
style = "#a7a7a7"
disabled = true

[hostname]
disabled = true
