format = "$sudo$username$hostname$character"
command_timeout = 1000

right_format = """
$hostname\
$directory\
$git_branch\
$git_status\
$git_commit\
$git_state\
$git_metrics\
$python"""

[directory]
truncation_length = 15
truncate_to_repo = false
fish_style_pwd_dir_length = 1
repo_root_style = "#ffffff underline"
read_only_style = "#ffffff"
before_repo_root_style = "#ffffff"
style = "#ffffff"
format = "[$path$read_only]($style)"
repo_root_format = "[>]($style) [$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($read_only_style) "
home_symbol = "~"
read_only = '!'
truncation_symbol = '.../'

[git_status]
format = " [$all_status$ahead_behind]($style) "
style = "#ffffff"
ahead = ">"
behind = "<"
diverged = "!"
renamed = "r"
deleted = "x"
disabled = true

[git_branch]
format = "[$symbol$branch]($style)"
symbol = ""
style = "#ffffff"

[git_metrics]
added_style = '#ffffff'
deleted_style = '#ffffff'
format = '( [↑$added]($added_style))([↓$deleted]($deleted_style) )'
disabled = false

[python]
symbol = ""
format = " [$symbol$virtualenv$version]($style)"
version_format = ".${minor}"
style = "#ffffff"
