[metadata]
# name = "active_theme"
name = "active_theme" # hardcode it so it's easy to switch out
author = "(me)"

# The most basic colors
[colors]
foreground = "#000000"
background = "#ffffff"

# Overrides the default cursor colors
cursor_bg = "#e8a447"
cursor_fg = "#000000"
cursor_border = "#e8a447"

# Color for selected text
selection_bg = "#f7e1c8"
selection_fg = "#000000"

# ANSI colors (colors 0-7)
ansi = [
  "#b9b9b9",
  "#8b4513",
  "#8e8e8e",
  "#800400",
  "#8b4513",
  "#747474",
  "#464646",
  "#fbe7c0"
]

# Bright variants of the ANSI colors (colors 8-15)
brights = [
  "#eeeeee",
  "#d9a164",
  "#b9b9b9",
  "#ffd3d3",
  "#b87333",
  "#8e8e8e",
  "#747474",
  "#fff8e1",
]

# [colors.tab_bar]
# background = "#b9b9b9"

[colors.tab_bar.active_tab]
bg_color = "#f7e1c8"
fg_color = "#000000"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
bg_color = "#eeeeee"
fg_color = "#fbe7c0"

[colors.tab_bar.new_tab]
bg_color = "#eeeeee"
fg_color = "#464646"
