# remapping copy/paste funcitonality for terminals

[*wezterm*]
alt.v = C-S-v
alt.c = C-S-c

[*Terminal]
alt.v = C-S-v
alt.c = C-S-c

[*konsole*]
alt.v = C-S-v
alt.c = C-S-c

[*ghostty*]
alt.v = C-S-v
alt.c = C-S-c

[kitty]
alt.v = C-S-v
alt.c = C-S-c

[foot]
alt.v = C-S-v
alt.c = C-S-c

[termite]
alt.v = C-S-v
alt.c = C-S-c

[alacritty]
alt.v = C-S-v
alt.c = C-S-c
