format = "$sudo$username$character"
command_timeout = 1000

right_format = """
$hostname\
$directory\
$git_branch\
$git_status\
$git_commit\
$git_state\
$git_metrics\
$python"""

[directory]
# truncation_length = 12
truncate_to_repo = true
fish_style_pwd_dir_length = 1
repo_root_style = "#616569 underline"
read_only_style = "#616569"
before_repo_root_style = "#616569"
style = "#616569"
format = "[$path]($style) "
repo_root_format = "[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($read_only_style) "
home_symbol = "~"
read_only = 'x'
truncation_symbol = '.../'

[git_status]
format = "[\\[$all_status$ahead_behind\\]]($style) "
style = "#616569"
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "x"
disabled = false

[git_branch]
format = "[$symbol $branch]($style) "
symbol = "|"
style = "#616569"

[git_metrics]
added_style = '#7abd91'
deleted_style = '#ff8989'
format = '([+$added]($added_style) )([-$deleted]($deleted_style) )'
disabled = false

[hostname]
format = "[$symbol$hostname]($style) "
trim_at = ""
ssh_only = true
ssh_symbol = "@"
style = "#616569"

[python]
symbol = ""
format = "[| $symbol$virtualenv \\[$version\\]]($style) "
version_format = "${major}.${minor}"
style = "#616569"
[line_break]
disabled = true

[character]
success_symbol = "[ >](#ffd700)"
error_symbol = "[ x](#ffd700 blink)"
vimcmd_symbol = "[ >](#ffd700)"
vimcmd_visual_symbol = "[ >](#ffd700 blink)"
vimcmd_replace_symbol = "[ _](#ffd700)"
vimcmd_replace_one_symbol = "[ _](#ffd700 blink)"

[cmd_duration]
disabled = true

[memory_usage]
disabled = true

[battery]
disabled = true

[username]
format = '[🌵](#ffd700)'
show_always = true

[sudo]
symbol = "."
format = '[$symbol](#ffd700) '
disabled = false

[package]
symbol = ".pkg"
format = '[$symbol](#616569) '
disabled = true

[perl]
symbol = ".pl"
format = '[$symbol](#616569) '
disabled = true

[php]
symbol = ".php"
format = '[$symbol](#616569) '
disabled = true

[pijul_channel]
symbol = "pijul"
format = '[$symbol](#616569) '
disabled = true

[pulumi]
symbol = ".yml"
format = '[$symbol](#616569) '
disabled = true

[purescript]
symbol = ".purs"
format = '[$symbol](#616569) '
disabled = true

[quarto]
symbol = ".qmd"
format = '[$symbol](#616569) '
disabled = true

[raku]
symbol = ".raku"
format = '[$symbol](#616569) '
disabled = true

[ruby]
symbol = ".rb"
format = '[$symbol](#616569) '
disabled = true

[rust]
symbol = ".rs"
format = '[$symbol](#616569) '
disabled = true

[scala]
symbol = ".sc"
format = '[$symbol](#616569) '
disabled = true

[spack]
symbol = "spack"
format = '[$symbol](#616569) '
disabled = true

[solidity]
symbol = ".sol"
format = '[$symbol](#616569) '
disabled = true

[status]
symbol = "x"

[swift]
symbol = ".swift"
format = '[$symbol](#616569) '
disabled = true

[typst]
symbol = "typst"
format = '[$symbol](#616569) '
disabled = true

[terraform]
symbol = ".tf"
format = '[$symbol](#616569) '
disabled = true

[zig]
symbol = ".zig"
format = '[$symbol](#616569) '
disabled = true

[aws]
symbol = ".aws"
format = '[$symbol](#616569) '
disabled = true

[azure]
symbol = ".az"
format = '[$symbol](#616569) '
disabled = true

[bun]
symbol = ".js"
format = '[$symbol](#616569) '
disabled = true

[c]
symbol = ".c"
format = '[$symbol](#616569) '
disabled = true

[cobol]
symbol = ".cbl"
format = '[$symbol](#616569) '
disabled = true

[conda]
symbol = ".conda"
format = '[$symbol](#616569) '
disabled = true

[crystal]
symbol = ".cr"
format = '[$symbol](#616569) '
disabled = true

[cmake]
symbol = ".cmake"
format = '[$symbol](#616569) '
disabled = true

[daml]
symbol = ".daml"
format = '[$symbol](#616569) '
disabled = true

[dart]
symbol = ".dart"
format = '[$symbol](#616569) '
disabled = true

[deno]
symbol = ".js"
format = '[$symbol](#616569) '
disabled = true

[dotnet]
symbol = ".net"
format = '[$symbol](#616569) '
disabled = true

[docker_context]
symbol = "docker "
format = '[$symbol](#616569) '
disabled = true

[elixir]
symbol = ".exs"
format = '[$symbol](#616569) '
disabled = true

[elm]
symbol = ".elm"
format = '[$symbol](#616569) '
disabled = true

[fennel]
symbol = ".fnl"
format = '[$symbol](#616569) '
disabled = true

[fossil_branch]
symbol = ".fossil"
format = '[$symbol](#616569) '
disabled = true

[gcloud]
symbol = ".gcp"
format = '[$symbol](#616569) '
disabled = true

[gleam]
symbol = ".gleam"
format = '[$symbol](#616569) '
disabled = true

[golang]
symbol = ".go"
format = '[$symbol](#616569) '
disabled = true

[gradle]
symbol = ".gradle"
format = '[$symbol](#616569) '
disabled = true

[guix_shell]
symbol = ".guix"
format = '[$symbol](#616569) '
disabled = true

[hg_branch]
symbol = ".hg"
format = '[$symbol](#616569) '
disabled = true

[java]
symbol = ".java"
format = '[$symbol](#616569) '
disabled = true

[julia]
symbol = ".jl"
format = '[$symbol](#616569) '
disabled = true

[kotlin]
symbol = ".kt"
format = '[$symbol](#616569) '
disabled = true

[lua]
symbol = ".lua"
format = '[$symbol](#616569) '
disabled = true

[nodejs]
symbol = ".js"
format = '[$symbol](#616569) '
disabled = true

[meson]
symbol = ".meson"
format = '[$symbol](#616569) '
disabled = true

[nats]
symbol = ".nats"
format = '[$symbol](#616569) '
disabled = true

[nim]
symbol = ".nim"
format = '[$symbol](#616569) '
disabled = true

[nix_shell]
symbol = ".nix"
format = '[$symbol](#616569) '
disabled = true

[ocaml]
symbol = ".ml"
format = '[$symbol](#616569) '
disabled = true

[opa]
symbol = ".opa"
format = '[$symbol](#616569) '
disabled = true

[os.symbols]
AIX = "aix"
Alpaquita = "alq"
AlmaLinux = "alma"
Alpine = "alp"
Amazon = "amz"
Android = "andr"
Arch = "rch"
Artix = "atx"
CentOS = "cent"
Debian = "deb"
DragonFly = "dfbsd"
Emscripten = "emsc"
EndeavourOS = "ndev"
Fedora = "fed"
FreeBSD = "fbsd"
Garuda = "garu"
Gentoo = "gent"
HardenedBSD = "hbsd"
Illumos = "lum"
Kali = "kali"
Linux = "lnx"
Mabox = "mbox"
Macos = "mac"
Manjaro = "mjo"
Mariner = "mrn"
MidnightBSD = "mid"
Mint = "mint"
NetBSD = "nbsd"
NixOS = "nix"
OpenBSD = "obsd"
OpenCloudOS = "ocos"
openEuler = "oeul"
openSUSE = "osuse"
OracleLinux = "orac"
Pop = "pop"
Raspbian = "rasp"
Redhat = "rhl"
RedHatEnterprise = "rhel"
RockyLinux = "rky"
Redox = "redox"
Solus = "sol"
SUSE = "suse"
Ubuntu = "ubnt"
Ultramarine = "ultm"
Unknown = "unk"
Void = "void"
Windows = "win"
