[metadata]
# name = "active_theme"
name = "active_theme" # hardcode it so it's easy to switch out
author = "(me)"

# The most basic colors
[colors]
foreground = "#000000"
background = "#ffffff"

# Overrides the default cursor colors
cursor_bg = "#b0ffb0"
cursor_fg = "#000000"
cursor_border = "#b0ffb0"

# Color for selected text
selection_bg = "#e6e8c8"
selection_fg = "#000000"

# ANSI colors (colors 0-7)
ansi = [
  "#bbbbbb",
  "#103310",
  "#707070",
  "#e67373",
  "#103310",
  "#484848",
  "#2e2e2e",
  "#dce8dc"
]

# Bright variants of the ANSI colors (colors 8-15)
brights = [
  "#ededed",
  "#6b876b",
  "#bbbbbb",
  "#ffe0e0",
  "#2a4c2a",
  "#707070",
  "#484848",
  "#f0fff0",
]

# [colors.tab_bar]
# background = "#bbbbbb"

[colors.tab_bar.active_tab]
bg_color = "#e6e8c8"
fg_color = "#000000"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
bg_color = "#ededed"
fg_color = "#dce8dc"

[colors.tab_bar.new_tab]
bg_color = "#ededed"
fg_color = "#2e2e2e"
