#!/bin/bash

SRC_DIR=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
export PYTHON_VENV_DIR="$HOME/.local/venvs"
export DEFAULT_PYTHON_NAME=python
export DEFAULT_PYPY_NAME=pypy

_optional() {
    if [ -e "$1" ]; then
        echo $1
    else
        echo $2
    fi
}

_find_newest_python() {
    for i in $(seq 15 -1 9); do
        if command -v "python3.${i}" 2>&1 >/dev/null; then
            PYTHON="python${PYTHON_V}"
            $PYTHON -m ensurepip
            echo "Found $PYTHON as most recent version..."
            _create_venv $PYTHON $DEFAULT_PYTHON_NAME $1
        fi
    done
}

_rm() {
  if [ -e "$1" ]; then
    echo "Removing $1..."
    if type -P rip >/dev/null 2>&1; then
      rip $1
    else
      rm -rf $1
    fi
  fi
}

_mkdir() {
    if [ ! -f $1 ]; then
        echo "Making directory $1..."
        mkdir -p $1
    fi
}

_create_venv() {
    echo "Creating $1 virtual environment '$2' using $3..."
    $1 -m venv $2
    source $2/bin/activate
    python -m ensurepip
    python -m pip install -r $3
    deactivate
}

__main__() {
    echo $SRC_DIR
    echo $PYTHON_VENV_DIR
    _mkdir "$PYTHON_VENV_DIR"
    cd $PYTHON_VENV_DIR

    if [ $# -eq 0 ]; then
        if [ -z "$2" ]; then
            _create_venv $1 $2 $SRC_DIR/default.txt
        else
            shortened="$(echo $1 | sed 's/python//g')"
            _create_venv $1 $shortened $SRC_DIR/default.txt
        fi
    else
        _find_newest_python $SRC_DIR/default.txt
        $PYTHON_VENV_DIR/$DEFAULT_PYTHON_NAME/bin/python3 -m pip install pipx
        export PYTHON_BIN="$PYTHON_VENV_DIR/$DEFAULT_PYTHON_NAME/bin"
    fi

    if command -v pypy3 2>&1 >/dev/null; then
        pypy3 -m ensurepip
        _create_venv pypy3 $DEFAULT_PYPY_NAME $SRC_DIR/pypy.txt
        export PYPY_BIN="$PYTHON_VENV_DIR/$DEFAULT_PYPY_NAME/bin"
    fi
}

__main__ $@
