[colors]
# ansi = [
#     "#595959",
#     "#656565",
#     "#717171",
#     "#7d7d7d",
#     "#898989",
#     "#959595",
#     "#a1a1a1",
#     "#adadad",
# ]
brights = [
  "#595959",
  "#737373",
  "#878787",
  "#9b9b9b",
  "#afafaf",
  "#c3c3c3",
  "#d7d7d7",
  "#ebebeb",
]
background = "#000000"
ansi = [
    "#878787",
    "#989898",
    "#a9a9a9",
    "#bbbbbb",
    "#cccccc",
    "#dddddd",
    "#eeeeee",
    "#ffffff",
]
cursor_bg = "#f6cd61"
cursor_border = "#f6cd61"
cursor_fg = "#000000"
foreground = "#eeeeee"
selection_bg = "#cccccc"
selection_fg = "#000000"

[colors.indexed]
16 = "#242424"
17 = "#242424"
18 = "#878787"
19 = "#f6cd61"
20 = "#b80d0d"
21 = "#dddddd"

[metadata]
aliases = []
author = "shane"
name = "blk"
