[metadata]
# name = "active_theme"
name = "active_theme" # hardcode it so it's easy to switch out
author = "(me)"

# The most basic colors
[colors]
foreground = "#ffffff"
background = "#1e1e1e"

# Overrides the default cursor colors
cursor_bg = "#e8a447"
cursor_fg = "#ffffff"
cursor_border = "#e8a447"

# Color for selected text
selection_bg = "#5a3a1f"
selection_fg = "#ffffff"

# ANSI colors (colors 0-7)
ansi = [
  "#6b6b6b",
  "#d4a97f",
  "#9e9e9e",
  "#ff4d4d",
  "#d4a97f",
  "#c4c4c4",
  "#e6e6e6",
  "#4a2d18"
]

# Bright variants of the ANSI colors (colors 8-15)
brights = [
  "#333333",
  "#7d5537",
  "#6b6b6b",
  "#a00000",
  "#aa7b52",
  "#9e9e9e",
  "#c4c4c4",
  "#2d1a0e",
]

# [colors.tab_bar]
# background = "#6b6b6b"

[colors.tab_bar.active_tab]
bg_color = "#5a3a1f"
fg_color = "#ffffff"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
bg_color = "#333333"
fg_color = "#4a2d18"

[colors.tab_bar.new_tab]
bg_color = "#333333"
fg_color = "#e6e6e6"
