[metadata]
# name = "active_theme"
name = "active_theme" # hardcode it so it's easy to switch out
author = "(me)"
background = "dark"

# The most basic colors
[colors]
foreground = "#ffffff"
background = "#1e1e1e"

# Overrides the default cursor colors
cursor_bg = "#bae847"
cursor_fg = "#ffffff"
cursor_border = "#bae847"

# Color for selected text
selection_bg = "#5e5e0a"
selection_fg = "#ffffff"

# ANSI colors (colors 0-7)
ansi = [
  "#6b6b6b",
  "#c2d4bc",
  "#9e9e9e",
  "#ff4d4d",
  "#c2d4bc",
  "#c4c4c4",
  "#e6e6e6",
  "#3a573e"
]

# Bright variants of the ANSI colors (colors 8-15)
brights = [
  "#333333",
  "#7d9b83",
  "#6b6b6b",
  "#a00000",
  "#a7c09f",
  "#9e9e9e",
  "#c4c4c4",
  "#293d2c",
]

# [colors.tab_bar]
# background = "#6b6b6b"

[colors.tab_bar.active_tab]
bg_color = "#5e5e0a"
fg_color = "#ffffff"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
bg_color = "#333333"
fg_color = "#3a573e"

[colors.tab_bar.new_tab]
bg_color = "#333333"
fg_color = "#e6e6e6"
